import com.liferay.gradle.plugins.go.tasks.ExecuteGoTask

import java.nio.file.Paths

buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.go", version: "latest.release"
	}

	repositories {
		maven {
			url file("../../../../.m2-tmp")
		}

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.go"

task compileInstaller(type: ExecuteGoTask)
task createInstaller(type: Copy)
task getInstallerDependencies(type: ExecuteGoTask)
task installComponentMavenArtifacts(type: Exec)
task installGox(type: ExecuteGoTask)
task packageInstaller(type: Zip)

defaultTasks "packageInstaller"

Date now = new Date()

compileInstaller {
	dependsOn getInstallerDependencies

	args "-osarch=\"darwin/amd64 linux/amd64 windows/amd64\"", "-output", "\"build/talend-installer/{{.Dir}}-{{.OS}}-{{.Arch}}\"", "installer"
	command "gox"
}

createInstaller {
	dependsOn compileInstaller

	from Paths.get("..", "tos-dependencies")
	into Paths.get("build", "talend-installer")
}

getInstallerDependencies {
	dependsOn installComponentMavenArtifacts
	dependsOn installGox

	args "mod", "tidy"
}

installComponentMavenArtifacts {
	if (File.pathSeparator.equals(";")) {
		commandLine "cmd.exe", "/c", "mvn clean install -f ./../pom.xml"
	}
	else {
		commandLine "/bin/sh", "-c", "mvn clean install -f ./../pom.xml"
	}
}

installGox {
	args "get", "-x", "-v", "github.com/mitchellh/gox"
}

packageInstaller {
	dependsOn createInstaller

	archiveName = "tLiferayComponents-TOS-7.1.1-${now.format('yyyyMMddHHmmss')}.zip"
	destinationDir = file("$buildDir/dist")

	from "$buildDir/talend-installer"
}