import com.liferay.gradle.util.FileUtil
import com.liferay.gradle.util.OSDetector
import com.liferay.gradle.util.StringUtil

import groovy.io.FileType

import java.util.concurrent.TimeUnit

buildscript {
	apply from: file("build-buildscript.gradle"), to: buildscript
}

task cleanElasticsearch(type: Delete)
task downloadElasticsearch(type: DownloadFileTask)
task setupElasticsearch
task setupXPackSecurity
task startElasticsearch
task startKibana
task stopElasticsearch
task stopKibana

String liferayHome = project.properties["liferay.home"]

int elasticsearchClusterSize = project.properties["elasticsearch.cluster.size"] as int
File elasticsearchDataDir = file("${liferayHome}/data/elasticsearch${project.'elasticsearch.major.version'}/repo")
File elasticsearchDir = file("${liferayHome}/elasticsearch-${project.'elasticsearch.version'}")

cleanElasticsearch {
	doLast {
		logger.lifecycle "Deleting {}", elasticsearchDataDir
		logger.lifecycle "Deleting {}", elasticsearchDir

		delete elasticsearchDataDir, elasticsearchDir

		File liferayHomeDir = file(liferayHome)

		liferayHomeDir.traverse(type: FileType.ANY, maxDepth: 0) {
			if (it.name.startsWith("elasticsearch-")) {
				logger.lifecycle "Deleting {}", it

				delete it
			}
		}
	}
}

downloadElasticsearch {
	mustRunAfter cleanElasticsearch

	destinationFile = file("${liferayHome}/${project.'elasticsearch.zip.name'}")
	url = project.properties["elasticsearch.zip.url"]

	doLast {
		project.copy {
			from zipTree(downloadElasticsearch.destinationFile)
			into liferayHome
		}
	}
}

setupXPackSecurity {
	mustRunAfter downloadElasticsearch

	doLast {
		project.exec {
			workingDir = file("${elasticsearchDir}/bin")

			if (OSDetector.isWindows()) {
				executable "cmd.exe"

				args "/c elasticsearch-certutil ca --pem --ca-dn CN=localhost --out elastic-stack-ca.zip"
			}
		}

		project.copy {
			from zipTree(file("${elasticsearchDir}/bin/elastic-stack-ca.zip"))
			into file("${elasticsearchDir}/bin")
		}

		delete file("${elasticsearchDir}/bin/elastic-stack-ca.zip")

		project.exec {
			workingDir = file("${elasticsearchDir}/bin")

			if (OSDetector.isWindows()) {
				executable "cmd.exe"

				args "/c elasticsearch-certutil cert --ca-cert ca/ca.crt --ca-key ca/ca.key --pem --ip 127.0.0.1 --dns localhost --name localhost --out certificate-bundle.zip"
			}
		}

		project.copy {
			from zipTree(file("${elasticsearchDir}/bin/certificate-bundle.zip"))
			into file("${elasticsearchDir}/bin")
		}

		ant.move(file: file("${elasticsearchDir}/bin/ca"), todir: file("${elasticsearchDir}/config/certs"))

		ant.move(file: file("${elasticsearchDir}/bin/localhost"), todir: file("${elasticsearchDir}/config/certs"))

		delete file("${elasticsearchDir}/bin/certificate-bundle.zip")

		File ymlFile = file("${elasticsearchDir}/config/elasticsearch.yml")

		ymlFile.append """
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.ssl.certificate: certs/localhost/localhost.crt
xpack.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]
xpack.ssl.key: certs/localhost/localhost.key"""
	}
}

setupElasticsearch {
	dependsOn cleanElasticsearch
	dependsOn downloadElasticsearch

	if (project.properties["elasticsearch.xpack.security.enabled"] == "true") {
		dependsOn setupXPackSecurity
	}

	doFirst {
		project.mkdir elasticsearchDataDir

		File configFile = file("${liferayHome}/osgi/configs/com.liferay.portal.search.elasticsearch${project.'elasticsearch.major.version'}.configuration.ElasticsearchConfiguration.config")

		configFile.text = "\noperationMode=\"REMOTE\""

		File ymlFile = file("${elasticsearchDir}/config/elasticsearch.yml")

		int minimumMasterNodes = (elasticsearchClusterSize / 2) + 1
		String pathRepo = elasticsearchDataDir.absolutePath.replace(File.separatorChar, '/' as char)

		ymlFile.append """
bootstrap.system_call_filter: false
cluster.name: LiferayElasticsearchCluster
discovery.zen.minimum_master_nodes: ${minimumMasterNodes}
path.repo: ${pathRepo}
xpack.ml.enabled: false
xpack.monitoring.collection.enabled: true"""
	}

	doLast {
		for (int i = 1; i <= elasticsearchClusterSize; i++) {
			project.copy {
				from elasticsearchDir
				into file("${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-${i}")
			}
		}

		delete elasticsearchDir
	}
}

startElasticsearch {
	if (project.properties["elasticsearch.xpack.security.enabled"] == "true") {
		finalizedBy startKibana
	}

	doFirst {
		for (int i = 1; i <= elasticsearchClusterSize; i++) {
			if (OSDetector.isWindows()) {
				ant.exec(dir: file("${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-${i}/bin"), executable: "cmd.exe", spawn: true) {
					arg(value: "/c")
					arg(value: "elasticsearch -d -p pid-elasticsearch")
				}
			}
		}
	}

	doLast {
		String elasticsearchURL = "http://localhost:9200/"
		boolean connected = false

		long startTime = System.currentTimeMillis()
		long waitTime = TimeUnit.SECONDS.toMillis(60)

		logger.lifecycle "Waiting for {}", elasticsearchURL

		while ((System.currentTimeMillis() - startTime) < waitTime) {
			URLConnection urlConnection = new URL(elasticsearchURL).openConnection()

			urlConnection.requestMethod = "HEAD"

			try {
				if (urlConnection.responseCode == 200) {
					connected = true

					break
				}
			}
			catch (IOException ioe) {
				sleep(500)
			}
		}

		if (!connected) {
			throw new GradleException("Unable to connect to Elasticsearch")
		}

		println file("${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/logs/LiferayElasticsearchCluster.log").text
	}
}

startKibana {
	doFirst {
		ByteArrayOutputStream standardByteArrayOutputStream = new ByteArrayOutputStream()

		project.exec {
			workingDir = file("${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/bin")
			standardOutput = standardByteArrayOutputStream

			if (OSDetector.isWindows()) {
				args "/c elasticsearch-setup-passwords auto --batch"
				executable "cmd.exe"
			}
		}

		String passwords = standardByteArrayOutputStream.toString()

		ant.propertyregex(
			input: "${passwords}",
			override: true,
			property: "kibanaPassword",
			regexp: "(PASSWORD kibana = )(\S*)",
			select: "\2"
		)

		ant.propertyregex(
			input: "${passwords}",
			override: true,
			property: "elasticPassword",
			regexp: "(PASSWORD elastic = )(\S*)",
			select: "\2"
		)

		standardByteArrayOutputStream = new ByteArrayOutputStream()

		project.exec {
			args "https://localhost:9200 -ku elastic:${elasticPassword}"
			executable "curl"
			standardOutput = standardByteArrayOutputStream
		}

		logger.lifecycle "Response: {}", standardByteArrayOutputStream.toString()

		standardByteArrayOutputStream = new ByteArrayOutputStream()

		project.exec {
			args "-k -X POST -ku elastic:${elasticPassword} https://localhost:9200/_xpack/license/start_trial?acknowledge=true&amp;pretty"
			executable "curl"
			standardOutput = standardByteArrayOutputStream
		}

		logger.lifecycle "Response: {}", standardByteArrayOutputStream.toString()

		ant.propertyregex(
			defaultValue: "${elasticPassword}"
			input: "${elasticPassword}",
			override: true,
			property: "osgiPassword",
			regexp: "=",
			replace: "\\\\="
		)

		File configFile = file("${liferayHome}/osgi/configs/com.liferay.portal.search.elasticsearch${project.'elasticsearch.major.version'}.xpack.monitoring.web.internal.configuration.XPackMonitoringConfiguration.config")

		configFile.append """
kibanaPassword="${osgiPassword}"
kibanaURL="https://localhost:5601"
proxyServletLogEnable="true""""

		configFile = file("${liferayHome}/osgi/configs/com.liferay.portal.search.elasticsearch${project.'elasticsearch.major.version'}.xpack.security.internal.configuration.XPackSecurityConfiguration.config")

		configFile.append """
certificateFormat="PEM"
password="${osgiPassword}"
requiresAuthentication="true"
sslCertificateAuthoritiesPaths="${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/ca/ca.crt"
sslCertificatePath="${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/localhost/localhost.crt"
sslKeyPath="${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/localhost/localhost.key"
transportSSLEnabled="true""""

		project.exec {
			workingDir = file("${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/bin")

			if (OSDetector.isWindows()) {
				args "/c elasticsearch-certutil cert --ca-cert ${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/ca/ca.crt --ca-key ${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/ca/ca.key --pass liferay --ip 127.0.0.1 --dns localhost --name localhost --out ${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/localhost.p12"
				executable "cmd.exe"
			}
		}

		project.exec {
			workingDir = file("${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/bin")

			if (OSDetector.isWindows()) {
				args "/c keytool -importkeystore -deststorepass liferay -destkeystore ${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/localhost.jks -srckeystore ${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/localhost.p12 -srcstoretype PKCS12 -srcstorepass liferay"
				executable "cmd.exe"
			}
		}

	if (project.properties["app.server.type"] == "true") {
		File setEnvBatFile = file("${project.'app.server.tomcat.dir'}/bin/setenv.bat")

		setEnvBatFile.append """
CATALINA_OPTS="${CATALINA_OPTS} -Djavax.net.ssl.trustStore=${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/localhost.jks -Djavax.net.ssl.trustStorePassword=liferay""""


		File setEnvShFile = file("${project.'app.server.tomcat.dir'}/bin/setenv.sh")

		setEnvShFile.append """
CATALINA_OPTS="${CATALINA_OPTS} -Djavax.net.ssl.trustStore=${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-1/config/certs/localhost.jks -Djavax.net.ssl.trustStorePassword=liferay""""
	}
	else {
		logger.lifecycle "Set setenv.bat and setenv.sh manually before attempting to connect with portal."
	}

	doLast {
		
	}
}

stopElasticsearch {
	doLast {
		for (int i = 1; i <= elasticsearchClusterSize; i++) {
			project.exec {
				workingDir = file("${liferayHome}/elasticsearch-${project.'elasticsearch.major.version'}/node-${i}")

				if (OSDetector.isWindows()) {
					executable "cmd.exe"

					args "/c for /f %x in (pid-elasticsearch) do taskkill /f /pid %x"
				}
			}
		}
	}
}

_createPluginTasks(elasticsearchDir)

private void _createPluginTasks(File elasticsearchDir) {
	project.properties.each {
		name, value ->

		if (name.startsWith("elasticsearch.plugins.") && name.endsWith(".zip.name")) {
			String pluginURL = project.properties[name.substring(0, name.length() - 4) + "url"]

			if (pluginURL != null) {
				String suffix = value.replaceAll(/[\.-](\w)/) {
					return it[1].toUpperCase()
				}

				Task downloadPluginTask = tasks.create(name: "downloadPlugin" + StringUtil.capitalize(suffix), type: DownloadFileTask) {
					destinationFile = project.file(project.properties["liferay.home"] + '/' + value)
					url = pluginURL
				}

				Task installPluginTask = tasks.create(name: "installPlugin" + StringUtil.capitalize(suffix), type: InstallPluginTask) {
					pluginFile = downloadPluginTask.destinationFile
					workingDir = file("${elasticsearchDir}/bin")

					if (name == "elasticsearch.plugins.ltr.zip.name") {
						input = "y"
					}
				}

				installPluginTask.mustRunAfter downloadPluginTask

				setupElasticsearch.dependsOn downloadPluginTask
				setupElasticsearch.dependsOn installPluginTask
			}
		}
	}
}

class DownloadFileTask extends DefaultTask {

	@TaskAction
	public void downloadFile() throws IOException {
		FileUtil.get(project, url, destinationFile, false, true)
	}

	File destinationFile
	String url

}

class InstallPluginTask extends Exec {

	@Override
	void exec() {
		if (OSDetector.isWindows()) {
			executable "cmd.exe"

			args "/c elasticsearch-plugin install file:///" + pluginFile
		}
		else {
			executable "/bin/sh"

			args "-c ./elasticsearch-plugin install file:///" + pluginFile
		}

		if (input != null) {
			standardInput = new ByteArrayInputStream(input.getBytes())
		}

		super.exec()
	}

	String input
	File pluginFile

}