#com.liferay.portal.tools.service.builder.version=1.0.228
org.gradle.configureondemand=true
org.gradle.daemon=false
systemProp.build.exclude.projects=modules
systemProp.build.exclude.dirs=\
	benchmarks,\
	classes,\
	out,\
	portal-client,\
	portal-impl,\
	portal-kernel,\
	portal-test,\
	portal-test-integration,\
	portal-web,\
	support-resin,\
	support-tomcat,\
	support-websphere,\
	sql,\
	tools,\
	util-bridges,\
	util-java,\
	util-slf4j,\
	util-taglib
