apply from: "../modules/build-portal.gradle"

dependencies {
    compileOnly group: “javax.portlet”, name: “portlet-api”, transitive: false, version: “3.0.1”
    compileOnly group: “javax.servlet”, name: “javax.servlet-api”, transitive: false, version: “3.1.0"
    compileOnly project(“:portal-kernel”)
}