dependencies {
	compile group: "com.liferay", name: "com.liferay.gradle.util", version: "1.0.31"

	compileOnly fileTree(builtBy: [rootProject.tasks.extractGradleApi214], dir: new File(rootProject.buildDir, "gradle-2.14"))
}

updateFileVersions {
	match(/classpath group: "com\.liferay", name: "com\.liferay\.gradle\.plugins\.poshi\.runner", version: "(\d.+)"/, "../../../portal-web/build-test.gradle")
}