buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins", version: "4.0.48"
	}

	repositories {
		File dir = rootProject.projectDir

		while (dir != null) {
			File tmpMavenRepositoryDir = new File(dir, ".m2-tmp")

			if (tmpMavenRepositoryDir.exists()) {
				maven {
					url tmpMavenRepositoryDir
				}
			}

			dir = dir.getParentFile();
		}

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.plugin"
apply plugin: "com.liferay.target.platform"

task runGradleTest
task pluginInfo

dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib"
	compileOnly group: "javax.portlet", name: "portlet-api"
	compileOnly group: "javax.servlet", name: "javax.servlet-api"
	compileOnly group: "jstl", name: "jstl"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations"

	targetPlatformBoms group: "com.liferay.portal", name: "release.portal.bom", version: "7.1.3"
	targetPlatformBoms group: "com.liferay.portal", name: "release.portal.bom.compile.only", version: "7.1.3"
	targetPlatformBoms group: "com.liferay.portal", name: "release.portal.bom.third.party", version: "7.1.3"

	targetPlatformDistro group: "com.liferay.portal", name: "release.portal.distro", version: "7.1.3"
}

repositories {
	maven {
		url "https://repository-cdn.liferay.com/nexus/content/groups/public"
	}
}

runGradleTest {
	dependsOn ":pluginInfo", ":resolve"
}

import java.nio.file.Files
import java.nio.file.FileSystem
import java.nio.file.FileSystems
import java.nio.file.FileVisitResult
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.SimpleFileVisitor
import java.nio.file.attribute.BasicFileAttributes

	pluginInfo {
		doLast {
			def appliedClasses = []
			def classesIds = [:]
			Set classpath = []

			plugins.each {
				appliedClasses << it.class.name
				it.class.classLoader.getURLs().each { classpath.add(it)}
				def jarUrl = it.class.protectionDomain.codeSource.location
				def pluginPath = Paths.get(jarUrl.toURI())
				def pluginUri = URI.create("jar:" + pluginPath.toUri())

				def jarFs

				try {
					jarFs = FileSystems.getFileSystem(pluginUri)
				}
				catch (Throwable t) {
				}

				if (jarFs == null) {
					jarFs = FileSystems.newFileSystem(pluginUri, Collections.emptyMap())
				}

				def gradlePlugins = jarFs.getPath("/META-INF/gradle-plugins")

				Files.walkFileTree(gradlePlugins, new SimpleFileVisitor<Path>() {
					@Override
					public FileVisitResult visitFile(Path path, BasicFileAttributes attrs) throws IOException {
						if (path.toString().endsWith(".properties")) {
							Properties properties = new Properties()
							properties.load(jarFs.provider.newInputStream(path))

							String implClass = properties.get("implementation-class")

							if (implClass != null) {
								classesIds.put(implClass, path.fileName.toString().replaceAll(".properties\$",""))
							}
						}

						return FileVisitResult.CONTINUE;
					}
				});
			}

			println "Plugin classpath..."

			classpath.each { println it }

			println "Applied ids..."

			def appliedIds = classesIds.findAll { appliedClasses.contains(it.key) }

			appliedIds.each { println "$it.value = $it.key" }

			println "\nTotal plugins applied = ${appliedIds.size()}"
		}
	}
