import com.liferay.gradle.plugins.gulp.ExecuteGulpTask

plugins {
	id "com.liferay.gulp"
}

node {
	useNpm = true
}

task runGradleTest

runGradleTest {
	dependsOn gulpHello

	doLast {
		File generatedFile = file("generated.txt")

		assert generatedFile.exists()
		assert generatedFile.text == "Hello World"
	}
}