<?xml version="1.0"?>

<project basedir="." default="compile" name="portal-test">
	<import file="../build-common-java.xml" />

	<property name="baseline.force.package.info" value="true" />
	<property name="deploy.dir" value="${liferay.home}/osgi/test" />
	<property name="jar.file" value="${ant.project.name}" />
	<property name="javac.classpathref" value="portal.test.classpath" />
	<property name="manifest.bundle.name" value="Liferay Portal Test" />
	<property name="manifest.bundle.symbolic.name" value="com.liferay.portal.test" />

	<path id="portal.test.classpath">
		<pathelement location="${project.dir}/portal-kernel/classes" />
		<path refid="lib.classpath" />
		<path refid="lib.pre.classpath" />
		<pathelement location="${project.dir}/modules/core/registry-api/classes" />
	</path>

	<target name="deploy">
		<if>
			<or>
				<equals arg1="${build.com.liferay.portal.snapshots}" arg2="true" />
				<equals arg1="${build.com.liferay.portal.test.version}" arg2=""/>
			</or>
			<then>
				<ant antfile="${project.dir}/build-common-java.xml" dir="${project.dir}/portal-test" inheritRefs="true" target="deploy" />
			</then>
			<else>
				<gradle-execute setupbinariescache="false" task="deployGroupPortalProject">
					<arg value="--build-file=${project.dir}/modules/util.gradle" />
					<arg value="-PdependencyName=${manifest.bundle.symbolic.name}" />
					<arg value="-PdeployDir=${deploy.dir}" />
					<arg value="-PprojectName=${ant.project.name}" />
				</gradle-execute>
			</else>
		</if>

		<move
			file="${deploy.dir}/${jar.file}.jar"
			tofile="${deploy.dir}/${manifest.bundle.symbolic.name}.jar"
		/>
	</target>
</project>