package ${package}.${template};

import com.liferay.portal.kernel.exception.ModelListenerException;
import com.liferay.portal.kernel.model.BaseModelListener;
import ${modelClassPackage}.${modelClassName};

import org.osgi.service.component.annotations.Component;

/**
 * @author ${author}
 */
@Component(immediate = true, service = ModelListener.class)
public class ${className}ModelListener extends BaseModelListener<${modelClassName}> {

	@Override
	public void onBeforeCreate(${modelClassName} model) throws ModelListenerException {
		System.out.println(
			"About to create layout: " + model.getNameCurrentValue());

		model.setTitle("Title generated by model listener!");
	}

}